name: Variables-practice
run-name: Variables-practice
on: workflow_dispatch
env:
  DAY_OF_WEEK : Monday
jobs:
  variables-practice:
    runs-on: macos-latest
    env:
        GREET: Hi! 
    steps:
      - name: Greeting
        run:  echo "$GREET, $NAME. Today is $DAY_OF_WEEK"
        env:
          NAME: James
